---
apiVersion: "v1"
kind: "Secret"
metadata:
  labels:
    app: {{ template "fleet.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fleet.fullname" . }}
data:
  foo: {{ .Files.Get "files/etc/foo.xml" | b64enc | quote}}
  bar: {{ .Values.Bar | b64enc | quote }}
