---
kind: "Service"
apiVersion: "v1"
metadata:
  annotations:
    ## These annontations mark the service as monitorable by Prometheus, both directly as a service level metric and
    ## via the blackbox exporter. For more information, see
    ## values.yaml
    prometheus.io/scrape: {{ .Values.monitoring.service.scrape | quote }}
    prometheus.io/probe: {{ .Values.monitoring.service.probe | quote }}
    prometheus.io/path: {{ .Values.monitoring.service.path | quote }}
    prometheus.io/port: {{ .Values.monitoring.service.port | quote }}
    ##
    ## If a load balancer is being used, ensure that the newer type of LB that passes along IP information is used
    ## rather than the legacy one.
    {{ if eq .Values.service.type "LoadBalancer" }}service.beta.kubernetes.io/external-traffic: "OnlyLocal"{{ end }}
  labels:
    app: {{ template "fleet.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fleet.fullname" . }}
spec:
  selector:
    app: {{ template "fleet.fullname" . }}
    release: "{{ .Release.Name }}"
  ports:
    - protocol: "TCP"
      name: "http"
      port: 8080
  type: {{ default "ClusterIP" .Values.service.type }}
  {{ if eq .Values.service.type "LoadBalancer" -}}
  {{ if .Values.service.loadBalancer.publicIp -}}
  loadBalancerIP: {{ .Values.service.loadBalancer.publicIp }}
  {{ if .Values.service.loadBalancer.allowedIps -}}
  loadBalancerSourceRanges:
{{ .Values.service.loadBalancer.allowedIps | toYaml | indent 4 }}
  {{ end -}}
  {{ end -}}
  {{ end -}}
