---
dependencies:
  - name: "mysql"
    # This version is the version in the file:
    #
    #   https://github.com/kubernetes/charts/blob/master/stable/mysql/Chart.yaml
    #
    # Tue 27 Mar 17:13:08 CEST 2018
    version: "0.3.6"
    repository: "https://kubernetes-charts.storage.googleapis.com"
  - name: "redis"
    # See above re. version constraints
    version: "1.1.21"
    repository: "https://kubernetes-charts.storage.googleapis.com"
